version: "3.9"

services:
  master:
    build:
      context: .
      dockerfile: master/Dockerfile
    container_name: master
    ports:
      - "9000:9000"
    volumes:
      - ./output:/app/output
      - ./log/log_master:/app/log/log_master
    networks:
      - mapreduce-net

  mapper:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - ROLE=mapper
      - PORT=9001
      - MASTER_ADDR=master:9000
    depends_on:
      - master
    volumes:
      - ./output:/app/output
      - ./log/log_worker:/app/log/log_worker
    networks:
      - mapreduce-net

  reducer:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - ROLE=reducer
      - PORT=9001
      - MASTER_ADDR=master:9000
    depends_on:
      - master
    volumes:
      - ./output:/app/output
      - ./log/log_worker:/app/log/log_worker
    networks:
      - mapreduce-net

networks:
  mapreduce-net:
    driver: bridge
